apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atmosphere.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atmosphere.labels" . | nindent 4 }}
  {{- with include "atmosphere.annotations" (dict "context" . "extraAnnotations" dict) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  PORT: "8080"
  ATMOSPHERE_DISABLE_MUX: {{ .Values.atmosphere.disableMux | quote }}
  {{- if .Values.atmosphere.disableTelemetry }}
  ATMOSPHERE_DISABLE_TELE: "true"
  {{- end }}
  {{- if .Values.atmosphere.publicUrl }}
  ATMOSPHERE_SITE_URL: {{ .Values.atmosphere.publicUrl | quote }}
  {{- else if and .Values.ingress.enabled .Values.ingress.hosts }}
  ATMOSPHERE_SITE_URL: {{ printf "%s://%s" (ternary "https" "http" (gt (len .Values.ingress.tls) 0)) (first .Values.ingress.hosts).host | quote }}
  {{- end }}
  {{- with .Values.atmosphere.dashboardUrl }}
  ATMOSPHERE_DASHBOARD_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.atmosphere.licenseKey }}
  ATMOSPHERE_LICENSE_KEY: {{ . | quote }}
  {{- end }}
  {{- if .Values.smtp.enabled }}
  ATMOSPHERE_SMTP_HOST: {{ .Values.smtp.host | quote }}
  ATMOSPHERE_SMTP_PORT: {{ .Values.smtp.port | quote }}
  ATMOSPHERE_SMTP_FROM: {{ .Values.smtp.from | quote }}
  {{- with .Values.smtp.username }}
  ATMOSPHERE_SMTP_USERNAME: {{ . | quote }}
  {{- end }}
  ATMOSPHERE_SMTP_SECURE: {{ .Values.smtp.secure | quote }}
  {{- end }}
  {{- if .Values.sso.oidc.enabled }}
  ATMOSPHERE_SSO: "oidc"
  ATMOSPHERE_OIDC_PROVIDER_NAME: {{ .Values.sso.oidc.providerName | quote }}
  {{- else if .Values.sso.saml.enabled }}
  ATMOSPHERE_SSO: "saml"
  ATMOSPHERE_SSO_SAML_PROVIDER_NAME: {{ .Values.sso.saml.providerName | quote }}
  {{- end }}
