<script setup lang="ts">
import type { ColumnReqType, ColumnType, TableType } from 'atmosphere-sdk'
import {
  PermissionEntity,
  PermissionKey,
  UITypes,
  UITypesName,
  isAutoGeneratedColumn,
  partialUpdateAllowedTypes,
  readonlyMetaAllowedTypes,
} from 'atmosphere-sdk'

interface Props {
  column: ColumnType
  required?: boolean | number
  hideMenu?: boolean
  hideIcon?: boolean
  hideIconTooltip?: boolean
  isHiddenCol?: boolean
  showLockIcon?: boolean
  showMenuMobile?: boolean
}

const props = defineProps<Props>()

const { isMobileMode } = useGlobal()

const isMobileMenuHidden = computed(() => props.hideMenu || (isMobileMode.value && !props.showMenuMobile))

const hideMenu = toRef(props, 'hideMenu')

const isGrid = inject(IsGridInj, ref(false))

const isForm = inject(IsFormInj, ref(false))

const isSurveyForm = inject(IsSurveyFormInj, ref(false))

const isExpandedForm = inject(IsExpandedFormOpenInj, ref(false))

const isExpandedBulkUpdateForm = inject(IsExpandedBulkUpdateFormOpenInj, ref(false))

const isDropDownOpen = ref(false)

const isPublic = inject(IsPublicInj, ref(false))

const meta = inject(MetaInj)!

const column = toRef(props, 'column')

const { isUIAllowed, isMetaReadOnly, sandboxRestrictionReason } = useRoles()

const { isAllowed } = usePermissions()

provide(ColumnInj, column)

const editColumnDropdown = ref(false)

const columnOrder = ref<Pick<ColumnReqType, 'column_order'> | null>(null)

const isAllowedToEditField = computed(() => {
  if (!props.showLockIcon || !column.value?.id) return true

  return isAllowed(PermissionEntity.FIELD, column.value.id, PermissionKey.RECORD_FIELD_EDIT)
})

const isSqlView = computed(() => (meta.value as TableType)?.type === 'view')

const columnTypeName = computed(() => {
  if (column.value.uidt === UITypes.LongText) {
    if (parseProp(column.value?.meta)?.richMode) {
      return UITypesName.RichText
    }

    if (parseProp(column.value?.meta)?.[LongTextAiMetaProp]) {
      return UITypesName.AIPrompt
    }
  }

  return column.value.uidt ? UITypesName[column.value.uidt] : ''
})

const addField = async (payload: any) => {
  columnOrder.value = payload
  editColumnDropdown.value = true
}

const editOrAddProviderRef = ref()

const enableDescription = ref(false)

watch(editColumnDropdown, (val) => {
  if (!val) {
    enableDescription.value = false
  }
})

const closeAddColumnDropdown = () => {
  columnOrder.value = null
  editColumnDropdown.value = false
}

const isColumnEditAllowed = computed(() => {
  if (
    isMetaReadOnly.value &&
    !readonlyMetaAllowedTypes.includes(column.value?.uidt) &&
    !partialUpdateAllowedTypes.includes(column.value?.uidt)
  )
    return false
  return true
})

const fieldEditReason = computed(() => (!isForm.value ? sandboxRestrictionReason('fieldEdit') : null))

const openHeaderMenu = (e?: MouseEvent, description = false) => {
  if (
    (isExpandedForm.value && e?.type === 'dblclick') ||
    isExpandedBulkUpdateForm.value ||
    isSqlView.value ||
    props.hideIconTooltip
  ) {
    return
  }

  if (
    !isForm.value &&
    (isUIAllowed('fieldEdit') || !!fieldEditReason.value) &&
    !isMobileMenuHidden.value &&
    (isColumnEditAllowed.value || description)
  ) {
    if (description) {
      enableDescription.value = true
    }
    editColumnDropdown.value = true
  }
}

const isDateDependencyField = computed(() => isColumnDateDependencyField(meta.value, column?.value?.id))

const openDropDown = (e: Event) => {
  if (isForm.value || (!isUIAllowed('fieldEdit') && !fieldEditReason.value && !isMobileMenuHidden.value) || props.hideIconTooltip)
    return

  e.preventDefault()
  e.stopPropagation()

  isDropDownOpen.value = !isDropDownOpen.value
}

const onVisibleChange = () => {
  editColumnDropdown.value = true
  if (!editOrAddProviderRef.value?.shouldKeepModalOpen?.()) {
    editColumnDropdown.value = false
    enableDescription.value = false
  }
}

const onClick = (e: Event) => {
  if (isMobileMenuHidden.value || (!isUIAllowed('fieldEdit') && !fieldEditReason.value) || props.hideIconTooltip) return

  // On mobile, only respond to clicks within the name wrapper
  if (isMobileMode.value && props.showMenuMobile) {
    const target = e.target as HTMLElement
    if (!target?.closest('.atm-cell-name-wrapper')) return
  }

  if (isDropDownOpen.value) {
    e.preventDefault()
    e.stopPropagation()
  } else {
    if (isExpandedForm.value && !editColumnDropdown.value && !isExpandedBulkUpdateForm.value) {
      isDropDownOpen.value = true
      return
    }
  }

  isDropDownOpen.value = false
}
</script>

<template>
  <div
    class="flex items-center w-full text-xs text-atm-content-gray-muted font-weight-medium group"
    :class="{
      'h-full': column,
      'flex-col !items-start justify-center pt-0.5': isExpandedForm && !isMobileMenuHidden && !isExpandedBulkUpdateForm,
      'atm-cell-expanded-form-header cursor-pointer hover:bg-atm-bg-gray-light':
        isExpandedForm &&
        !isMobileMenuHidden &&
        !isMobileMode &&
        (isUIAllowed('fieldEdit') || !!fieldEditReason) &&
        !isExpandedBulkUpdateForm,
      'cursor-pointer':
        isExpandedForm &&
        !isMobileMenuHidden &&
        isMobileMode &&
        (isUIAllowed('fieldEdit') || !!fieldEditReason) &&
        !isExpandedBulkUpdateForm,
      'bg-atm-bg-gray-light':
        isExpandedForm && !isMobileMode && !isExpandedBulkUpdateForm ? editColumnDropdown || isDropDownOpen : false,
    }"
    @dblclick="openHeaderMenu($event, false)"
    @click.right="openDropDown"
    @click="onClick"
  >
    <div
      class="atm-cell-name-wrapper flex items-center"
      :class="{
        'w-full flex-1': !(isMobileMode && props.showMenuMobile && isExpandedForm),
        'max-w-[calc(100%_-_23px)]': !isExpandedForm && !column.description?.length,
        'max-w-[calc(100%_-_44px)]': !isExpandedForm && column.description?.length,
        'max-w-full': isExpandedForm && !isExpandedBulkUpdateForm,
      }"
    >
      <template v-if="column && !props.hideIcon">
        <AtTooltip
          v-if="isGrid"
          class="flex items-center"
          placement="bottom"
          :disabled="
            hideIconTooltip || (isExpandedForm && !isExpandedBulkUpdateForm ? editColumnDropdown || isDropDownOpen : false)
          "
        >
          <template #title> {{ columnTypeName }} </template>
          <SmartsheetHeaderCellIcon
            :class="{
              'self-start': isForm || isSurveyForm,
            }"
          />
        </AtTooltip>
        <SmartsheetHeaderCellIcon
          v-else
          :class="{
            'self-start': isForm || isSurveyForm,
          }"
        />
      </template>
      <AtTooltip
        v-if="column"
        :class="{
          'cursor-pointer': !isForm && (isUIAllowed('fieldEdit') || !!fieldEditReason) && !hideMenu,
          'cursor-default': isForm || (!isUIAllowed('fieldEdit') && !fieldEditReason) || hideMenu,
          'truncate': !isForm,
        }"
        class="name pl-1 max-w-full rtl:(pr-1 pl-0)"
        placement="bottom"
        show-on-truncate-only
        :disabled="isExpandedForm && !isExpandedBulkUpdateForm ? editColumnDropdown || isDropDownOpen : false"
      >
        <template #title> {{ column.title }} </template>

        <span
          :data-test-id="column.title"
          :class="{
            'select-none': isExpandedForm && !isExpandedBulkUpdateForm,
          }"
        >
          {{ column.title }}
        </span>
      </AtTooltip>

      <span v-if="(column.rqd && !column.cdf) || required" class="text-atm-content-red-medium">&nbsp;*</span>

      <PermissionsTooltip
        v-if="!isAllowedToEditField"
        :entity="PermissionEntity.FIELD"
        :entity-id="column.id"
        :permission="PermissionKey.RECORD_FIELD_EDIT"
        :show-pointer-event-none="false"
        hide-on-click
        class="!ml-1 flex children:flex"
      >
        <GeneralIcon icon="ncLock" class="atm-column-lock-icon flex-none w-3.5 h-3.5 opacity-90" />
      </PermissionsTooltip>

      <GeneralIcon
        v-if="
          isExpandedForm && !isExpandedBulkUpdateForm && !isMobileMenuHidden && (isUIAllowed('fieldEdit') || !!fieldEditReason)
        "
        icon="arrowDown"
        class="atm-column-context-menu flex-none cursor-pointer ml-1 group-hover:visible w-4 h-4"
        :class="{
          visible: editColumnDropdown || isDropDownOpen,
          invisible: !(editColumnDropdown || isDropDownOpen),
        }"
      />
      <SmartsheetHeaderDescriptionTooltip
        v-if="column.description?.length && isExpandedForm && !hideMenu"
        :description="column.description"
      />
      <div class="flex-1" />
      <AtTooltip v-if="isDateDependencyField && isExpandedForm && !isPublic" class="flex items-center" placement="bottom">
        <template #title> {{ $t('labels.dateDependency.enabled') }} </template>
        <GeneralIcon icon="gantt" class="flex-none !w-3.5 !h-3.5 !text-atm-content-gray-muted" />
      </AtTooltip>
      <AtTooltip
        v-if="column.readonly && !isAutoGeneratedColumn(column) && meta?.synced && isExpandedForm && !isPublic"
        class="flex items-center"
        placement="bottom"
      >
        <template #title> {{ $t('tooltip.fieldIsExternallySynced') }} </template>
        <GeneralIcon icon="ncZap" class="flex-none !w-3.5 !h-3.5 !text-atm-content-gray-disabled" />
      </AtTooltip>
    </div>
    <SmartsheetHeaderDescriptionTooltip
      v-if="column.description?.length && isPublic && isGrid && !isExpandedForm && !hideMenu"
      :description="column.description"
      variant="grid"
    />

    <template v-if="!hideMenu || meta?.synced">
      <div v-if="!isExpandedForm" class="flex-1" />

      <div v-if="!isExpandedForm && meta?.synced && column.readonly && !isAutoGeneratedColumn(column)">
        <AtTooltip class="flex items-center" placement="bottom">
          <template #title> {{ $t('tooltip.fieldIsExternallySynced') }} </template>
          <GeneralIcon icon="ncZap" class="flex-none !w-4 !h-4 !text-atm-content-gray-disabled" />
        </AtTooltip>
      </div>
      <LazySmartsheetHeaderMenu
        v-else-if="!isForm && (isUIAllowed('fieldEdit') || !!fieldEditReason)"
        v-model:is-open="isDropDownOpen"
        :is-hidden-col="isHiddenCol"
        @add-column="addField"
        @edit="openHeaderMenu"
      />
    </template>

    <a-dropdown
      v-model:visible="editColumnDropdown"
      class="h-full"
      :trigger="['click']"
      :placement="isExpandedForm && !isExpandedBulkUpdateForm ? 'bottomLeft' : 'bottomRight'"
      :overlay-class-name="`atm-dropdown-edit-column ${editColumnDropdown ? 'active rounded-2xl' : ''}`"
      @visible-change="onVisibleChange"
    >
      <div v-if="isExpandedForm && !isExpandedBulkUpdateForm" class="h-[1px]" @dblclick.stop>&nbsp;</div>
      <div v-else />

      <template #overlay>
        <div class="atm-edit-or-add-provider-wrapper">
          <LazySmartsheetColumnEditOrAddProvider
            v-if="editColumnDropdown"
            ref="editOrAddProviderRef"
            :column="columnOrder ? null : column"
            :column-position="columnOrder"
            class="w-full"
            :edit-description="enableDescription"
            @submit="closeAddColumnDropdown"
            @cancel="closeAddColumnDropdown"
            @click.stop
            @keydown.stop
          />
        </div>
      </template>
    </a-dropdown>
  </div>
</template>

<style scoped>
.name {
  max-width: calc(100% - 10px);
  word-break: break-word;
  white-space: pre-line;
}
</style>
