<script lang="ts" setup>
import type { ColumnType } from 'atmosphere-sdk'
import { isColumnInvalid } from '#imports'

const props = defineProps<{ virtual?: boolean; isOpen: boolean; isHiddenCol?: boolean }>()

const emit = defineEmits(['edit', 'addColumn', 'update:isOpen'])

const isOpen = useVModel(props, 'isOpen', emit)

const column = inject(ColumnInj)

const isLocked = inject(IsLockedInj, ref(null))

const isPublic = inject(IsPublicInj, ref(false))

const isExpandedForm = inject(IsExpandedFormOpenInj, ref(false))

const meta = inject(MetaInj, ref())

const { isUIAllowed } = useRoles()

const { aiIntegrations, isAtmosphereAiAvailable } = useAtmosphereAi()

const columnInvalid = computed<{ isInvalid: boolean; tooltip: string }>(() => {
  if (!column?.value) {
    return {
      isInvalid: false,
      tooltip: '',
    }
  }

  return isColumnInvalid({
    col: column.value,
    aiIntegrations: aiIntegrations.value,
    isReadOnly: isPublic.value || !isUIAllowed('dataEdit'),
    isAtmosphereAiAvailable: isAtmosphereAiAvailable.value,
    columns: meta.value?.columns as ColumnType[],
  })
})

const isDateDependencyField = computed(() => isColumnDateDependencyField(meta.value, column?.value?.id))

const openDropdown = () => {
  if (isLocked.value) return
  isOpen.value = !isOpen.value
}

const emitAddColumn = (...args: any[]) => {
  emit('addColumn', ...args)
}

const emitEdit = (...args: any[]) => {
  emit('edit', ...args)
}
</script>

<template>
  <a-dropdown
    v-model:visible="isOpen"
    :trigger="['click']"
    :placement="isExpandedForm ? 'bottomLeft' : 'bottomRight'"
    :overlay-class-name="`atm-dropdown-column-operations ${isOpen ? 'active' : ''} !border-1 rounded-lg !shadow-xl`"
    @click.stop="openDropdown"
  >
    <div class="flex gap-1 items-center" @dblclick.stop>
      <div v-if="isExpandedForm" class="h-[1px]">&nbsp;</div>
      <SmartsheetHeaderDescriptionTooltip
        v-if="column?.description?.length && !isExpandedForm"
        :description="column?.description"
        variant="grid"
      />

      <AtTooltip class="flex items-center">
        <GeneralIcon
          v-if="columnInvalid.isInvalid && !isExpandedForm"
          class="text-atm-content-red-light w-3.5 h-3.5"
          icon="alertTriangle"
        />

        <template #title>
          {{ $t(columnInvalid.tooltip) }}
        </template>
      </AtTooltip>
      <AtTooltip v-if="isDateDependencyField && !isExpandedForm && !isPublic" class="flex items-center" placement="bottom">
        <template #title> {{ $t('labels.dateDependency.enabled') }} </template>
        <GeneralIcon icon="gantt" class="flex-none !w-3.5 !h-3.5 !text-atm-content-gray-muted" />
      </AtTooltip>
      <template v-if="meta?.synced && column?.readonly && !isAutoGeneratedColumn(column) && !isExpandedForm && !isPublic">
        <GeneralIcon class="!text-atm-content-gray-disabled cursor-pointer" icon="ncZap" />
      </template>
      <GeneralIcon
        v-else-if="!isExpandedForm"
        icon="arrowDown"
        class="text-atm-content-gray-muted h-full atm-ui-dt-dropdown cursor-pointer outline-0 mr-2"
      />
    </div>
    <template #overlay>
      <SmartsheetHeaderColumnMenu
        v-model:is-open="isOpen"
        :column="column"
        :virtual="virtual"
        :is-hidden-col="isHiddenCol"
        @add-column="emitAddColumn"
        @edit="emitEdit"
      />
    </template>
  </a-dropdown>
</template>

<style scoped lang="scss">
:deep(.atm-menu-item-inner) {
  @apply !w-full;
}
.atm-header-menu-item {
  @apply text-dropdown flex items-center gap-2;
}

.atm-column-options {
  .atm-icons {
    @apply !w-5 !h-5;
  }
}

:deep(.ant-dropdown-menu-item.ant-dropdown-menu-item-disabled .atm-icon) {
  @apply text-current;
}
</style>
