version: '3'

x-uffizzi:
  ingress:
    service: atmosphere
    port: 8080

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
    deploy:
      resources:
        limits:
          memory: 500M
  mysql:
    environment:
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: atmosphere
    image: "mysql:8.3.0"
    deploy:
      resources:
        limits:
          memory: 500M
  atmosphere:
    image: "${ATMOSPHERE_IMAGE}"
    ports:
      - "8080:8080"
    entrypoint: /bin/sh
    command: ["-c", "apk add wait4ports && wait4ports tcp://localhost:5432 && /usr/src/appEntry/start.sh"]
    environment:
      ATMOSPHERE_DB: "pg://localhost:5432?u=postgres&p=password&d=root_db"
      ATMOSPHERE_ADMIN_EMAIL: admin@atmosphere.dev
      ATMOSPHERE_ADMIN_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 500M