export enum MetaTable {
  PROJECT = 'atm_bases_v2',
  SOURCES = 'atm_sources_v2',
  SOURCES_OLD = SOURCES,
  MODELS = 'atm_models_v2',
  COLUMNS = 'atm_columns_v2',
  COLUMN_VALIDATIONS = 'atm_columns_validations_v2',
  COL_PROPS = 'atm_col_props_v2',
  COL_RELATIONS = 'atm_col_relations_v2',
  COL_SELECT_OPTIONS = 'atm_col_select_options_v2',
  COL_LOOKUP = 'atm_col_lookup_v2',
  COL_ROLLUP = 'atm_col_rollup_v2',
  COL_FORMULA = 'atm_col_formula_v2',
  COL_QRCODE = 'atm_col_qrcode_v2',
  COL_BARCODE = 'atm_col_barcode_v2',
  COL_LONG_TEXT = 'atm_col_long_text_v2',
  FILTER_EXP = 'atm_filter_exp_v2',
  // HOOK_FILTER_EXP = 'atm_hook_filter_exp_v2',
  SORT = 'atm_sort_v2',
  SHARED_VIEWS = 'atm_shared_views_v2',
  ACL = 'atm_acl_v2',
  FORM_VIEW = 'atm_form_view_v2',
  FORM_VIEW_COLUMNS = 'atm_form_view_columns_v2',
  GALLERY_VIEW = 'atm_gallery_view_v2',
  GALLERY_VIEW_COLUMNS = 'atm_gallery_view_columns_v2',
  CALENDAR_VIEW = 'atm_calendar_view_v2',
  CALENDAR_VIEW_COLUMNS = 'atm_calendar_view_columns_v2',
  CALENDAR_VIEW_RANGE = 'atm_calendar_view_range_v2',
  TIMELINE_VIEW = 'atm_timeline_view_v2',
  TIMELINE_VIEW_COLUMNS = 'atm_timeline_view_columns_v2',
  TIMELINE_VIEW_RANGE = 'atm_timeline_view_range_v2',
  GANTT_VIEW = 'atm_gantt_view_v2',
  GANTT_VIEW_COLUMNS = 'atm_gantt_view_columns_v2',
  GRID_VIEW = 'atm_grid_view_v2',
  GRID_VIEW_COLUMNS = 'atm_grid_view_columns_v2',
  KANBAN_VIEW = 'atm_kanban_view_v2',
  KANBAN_VIEW_COLUMNS = 'atm_kanban_view_columns_v2',
  USERS = 'atm_users_v2',
  ORGS_OLD = 'atm_orgs_v2',
  TEAMS_OLD = 'atm_teams_v2',
  TEAM_USERS_OLD = 'atm_team_users_v2',
  VIEWS = 'atm_views_v2',
  AUDIT = 'atm_audit_v2',
  HOOKS = 'atm_hooks_v2',
  HOOK_LOGS = 'atm_hook_logs_v2',
  HOOK_TRIGGER_FIELDS = 'atm_hook_trigger_fields',
  PLUGIN = 'atm_plugins_v2',
  PROJECT_USERS = 'atm_base_users_v2',
  MODEL_ROLE_VISIBILITY = 'atm_disabled_models_for_role_v2',
  API_TOKENS = 'atm_api_tokens',
  BOOKMARK_GROUPS = 'atm_bookmark_groups',
  BOOKMARKS = 'atm_bookmarks',
  MAIL_SENDS = 'atm_mail_sends',
  SYATMOSPHERE_SOURCE = 'atm_sync_source_v2',
  SYATMOSPHERE_LOGS = 'atm_sync_logs_v2',
  MAP_VIEW = 'atm_map_view_v2',
  MAP_VIEW_COLUMNS = 'atm_map_view_columns_v2',
  LIST_VIEW = 'atm_list_view_v2',
  LIST_VIEW_COLUMNS = 'atm_list_view_columns_v2',
  LIST_VIEW_LEVELS = 'atm_list_view_levels_v2',
  DATE_DEPENDENCY = 'atm_date_dependency_v2',
  STORE = 'atm_store',
  NOTIFICATION = 'notification',
  USER_REFRESH_TOKENS = 'atm_user_refresh_tokens',
  EXTENSIONS = 'atm_extensions',
  BASE_VARIABLES = 'atm_base_variables',
  COMMENTS = 'atm_comments',
  USER_COMMENTS_NOTIFICATIONS_PREFERENCE = 'atm_user_comment_notifications_preference',
  COMMENTS_REACTIONS = 'atm_comment_reactions',
  JOBS = 'atm_jobs',
  INTEGRATIONS = 'atm_integrations_v2',
  INTEGRATIONS_STORE = 'atm_integrations_store_v2',
  INTEGRATION_LINKS = 'atm_integration_links_v2',
  FILE_REFERENCES = 'atm_file_references',
  COL_BUTTON = 'atm_col_button_v2',
  SNAPSHOT = 'atm_snapshots',
  SNAPSHOT_SCHEDULE = 'atm_snapshot_schedules',
  ROW_COLOR_CONDITIONS = 'atm_row_color_conditions',
  DATA_REFLECTION = 'atm_data_reflection',
  CUSTOM_URLS = 'atm_custom_urls_v2',
  SYATMOSPHERE_CONFIGS = 'atm_sync_configs',
  SYATMOSPHERE_MAPPINGS = 'atm_sync_mappings',
  TABLE_SYNCS = 'atm_table_syncs',
  TABLE_SYATMOSPHERE_MAPPINGS = 'atm_table_sync_mappings',
  TABLE_SYATMOSPHERE_COLUMN_MAPPINGS = 'atm_table_sync_column_mappings',
  USAGE_STATS = 'atm_usage_stats',
  MCP_TOKENS = 'atm_mcp_tokens',
  DB_SERVERS = 'atm_db_servers',
  TEAMS = 'atm_teams',
  TEAM_USERS = 'atm_team_users',
  PERMISSIONS = 'atm_permissions',
  PERMISSION_SUBJECTS = 'atm_permission_subjects',
  PRINCIPALS = 'atm_principals',
  PRINCIPAL_ASSIGNMENTS = 'atm_principal_assignments',
  DASHBOARDS = 'atm_dashboards_v2',
  WIDGETS = 'atm_widgets_v2',
  INTERFACES = 'atm_interfaces',
  INTERFACE_PAGES = 'atm_interface_pages',
  OAUTH_CLIENTS = 'atm_oauth_clients',
  OAUTH_AUTHORIZATION_CODES = 'atm_oauth_authorization_codes',
  OAUTH_TOKENS = 'atm_oauth_tokens',

  LAYOUT = 'atm_ds_layout_v2',
  WIDGET = 'atm_ds_widget_v2',
  DASHBOARD_PROJECT_DB_PROJECT_LINKINGS = 'atm_ds_dashboard_project_db_project_linkings_v2',
  WIDGET_DB_DEPENDENCIES = 'atm_ds_widget_db_dependencies_v2',
  BOOK = 'atm_books',
  WORKSPACE = 'workspace',
  WORKSPACE_USER = 'workspace_user',
  FOLLOWER = 'atm_follower',
  COWRITER = 'cowriter',
  MODEL_STAT = 'atm_model_stats_v2',
  DB_MUX = 'atm_sql_executor_v2',
  SSO_CLIENT = 'atm_sso_client',
  SSO_CLIENT_DOMAIN = 'atm_sso_client_domain',
  ORG_DOMAIN = 'atm_org_domain',
  ORG = 'atm_org',
  ORG_USERS = 'atm_org_users',
  PLANS = 'atm_plans',
  SUBSCRIPTIONS = 'atm_subscriptions',
  ADDONS = 'atm_addons',
  SUBSCRIPTION_ADDONS = 'atm_subscription_addons',
  CREDIT_GRANTS = 'atm_credit_grants',
  CREDIT_LEDGER = 'atm_credit_ledger',
  CREDIT_HOLDS = 'atm_credit_holds',
  CREDIT_METERING_COUNTERS = 'atm_credit_metering_counters',
  AUTOMATIONS = 'atm_automations',
  AUTOMATION_EXECUTIONS = 'atm_automation_executions',
  DEPENDENCY_TRACKER = 'atm_dependency_tracker',
  INSTALLATIONS = 'atm_installations',
  GCP_MARKETPLACE_ACCOUNTS = 'atm_gcp_marketplace_accounts',
  GCP_MARKETPLACE_ENTITLEMENTS = 'atm_gcp_marketplace_entitlements',
  SANDBOXES_OLD = 'atm_sandboxes',
  SANDBOX_VERSIONS_OLD = 'atm_sandbox_versions',
  SANDBOX_DEPLOYMENT_LOGS_OLD = 'atm_sandbox_deployment_logs',
  MANAGED_APPS = 'atm_managed_apps',
  MANAGED_APP_VERSIONS = 'atm_managed_app_versions',
  MANAGED_APP_DEPLOYMENT_LOGS = 'atm_managed_app_deployment_logs',
  AUTOMATION_SUBSCRIBERS = 'atm_automation_subscribers',
  SANDBOXES = 'atm_sandboxes_v2',
  SANDBOX_CHANGELOG = 'atm_sandbox_changelog',
  OPERATION_LOGS = 'atm_operation_logs',
  SCIM_CONFIG = 'atm_scim_config',
  RECORD_TEMPLATES = 'atm_record_templates',
  RLS_POLICIES = 'atm_rls_policies',
  RLS_POLICY_SUBJECTS = 'atm_rls_policy_subjects',
  VIEW_SECTIONS = 'atm_view_sections',
  BASE_SECTIONS = 'atm_base_sections',
  CHAT_SESSIONS = 'atm_chat_sessions',
  CHAT_MESSAGES = 'atm_chat_messages',
  /** @deprecated Documents now live in atm_models_v2 (type='document'). Kept for legacy data cleanup. */
  DOCS = 'atm_docs_v2',
  DOC_CONTENT = 'atm_doc_content_v2',
  DOC_REVISIONS = 'atm_doc_revisions_v2',
  API_TOKEN_SCOPES = 'atm_api_token_scopes',
  TRASH = 'atm_trash',
}

export const BaseRelatedMetaTables = [
  MetaTable.CALENDAR_VIEW_COLUMNS,
  MetaTable.CALENDAR_VIEW_RANGE,
  MetaTable.CALENDAR_VIEW,
  MetaTable.TIMELINE_VIEW_COLUMNS,
  MetaTable.TIMELINE_VIEW_RANGE,
  MetaTable.TIMELINE_VIEW,
  MetaTable.GANTT_VIEW_COLUMNS,
  MetaTable.GANTT_VIEW,
  MetaTable.COL_BARCODE,
  MetaTable.COL_BUTTON,
  MetaTable.COL_FORMULA,
  MetaTable.COL_LONG_TEXT,
  MetaTable.COL_LOOKUP,
  MetaTable.COL_QRCODE,
  MetaTable.COL_RELATIONS,
  MetaTable.COL_ROLLUP,
  MetaTable.COL_SELECT_OPTIONS,
  MetaTable.COLUMNS,
  MetaTable.COMMENTS_REACTIONS,
  MetaTable.COMMENTS,
  MetaTable.CUSTOM_URLS,
  MetaTable.DASHBOARDS,
  MetaTable.MODEL_ROLE_VISIBILITY,
  MetaTable.EXTENSIONS,
  MetaTable.FILTER_EXP,
  MetaTable.FORM_VIEW_COLUMNS,
  MetaTable.FORM_VIEW,
  MetaTable.GALLERY_VIEW_COLUMNS,
  MetaTable.GALLERY_VIEW,
  MetaTable.GRID_VIEW_COLUMNS,
  MetaTable.GRID_VIEW,
  MetaTable.HOOK_LOGS,
  MetaTable.HOOKS,
  MetaTable.KANBAN_VIEW_COLUMNS,
  MetaTable.KANBAN_VIEW,
  MetaTable.MAP_VIEW_COLUMNS,
  MetaTable.MAP_VIEW,
  MetaTable.LIST_VIEW_COLUMNS,
  MetaTable.LIST_VIEW_LEVELS,
  MetaTable.LIST_VIEW,
  MetaTable.DATE_DEPENDENCY,
  MetaTable.MCP_TOKENS,
  MetaTable.MODELS,
  MetaTable.PERMISSIONS,
  MetaTable.PERMISSION_SUBJECTS,
  MetaTable.RLS_POLICIES,
  MetaTable.RLS_POLICY_SUBJECTS,
  MetaTable.ROW_COLOR_CONDITIONS,
  MetaTable.SORT,
  MetaTable.SOURCES,
  MetaTable.SYATMOSPHERE_CONFIGS,
  MetaTable.SYATMOSPHERE_LOGS,
  MetaTable.SYATMOSPHERE_MAPPINGS,
  MetaTable.SYATMOSPHERE_SOURCE,
  MetaTable.TABLE_SYNCS,
  MetaTable.TABLE_SYATMOSPHERE_MAPPINGS,
  MetaTable.TABLE_SYATMOSPHERE_COLUMN_MAPPINGS,
  MetaTable.VIEWS,
  MetaTable.WIDGETS,
  MetaTable.BASE_VARIABLES,
  MetaTable.MODEL_STAT,
  MetaTable.AUTOMATIONS,
  MetaTable.AUTOMATION_EXECUTIONS,
  MetaTable.DEPENDENCY_TRACKER,
  MetaTable.DOCS,
  MetaTable.DOC_CONTENT,
  MetaTable.DOC_REVISIONS,
  MetaTable.TRASH,
];

export enum MetaTableOldV2 {
  PROJECT = 'atm_projects_v2',
  PROJECT_USERS = 'atm_project_users_v2',
  BASES = 'atm_bases_v2',
  LAYOUT = 'atm_ds_layout_v2',
  WIDGET = 'atm_ds_widget_v2',
  DASHBOARD_PROJECT_DB_PROJECT_LINKINGS = 'atm_ds_dashboard_project_db_project_linkings_v2',
  WIDGET_DB_DEPENDENCIES = 'atm_ds_widget_db_dependencies_v2',
  WORKFLOWS = 'atm_workflows',
  WORKFLOW_EXECUTIONS = 'atm_workflow_executions',
  SCRIPTS = 'atm_scripts',
  OUTLINE_VIEW = 'atm_outline_view_v2',
  OUTLINE_VIEW_COLUMNS = 'atm_outline_view_columns_v2',
  OUTLINE_VIEW_LEVELS = 'atm_outline_view_levels_v2',
}

export const orderedMetaTables = [
  // Misc leaf tables
  MetaTable.MODEL_ROLE_VISIBILITY,
  MetaTable.PLUGIN,
  MetaTable.AUDIT,
  MetaTable.ACL,

  // Team / Permission (children before parents)
  MetaTable.TEAM_USERS,
  MetaTable.TEAMS,
  MetaTable.TEAM_USERS_OLD,
  MetaTable.TEAMS_OLD,
  MetaTable.PRINCIPAL_ASSIGNMENTS,
  MetaTable.PRINCIPALS,
  MetaTable.PERMISSION_SUBJECTS,
  MetaTable.PERMISSIONS,

  // Org
  MetaTable.ORG_USERS,
  MetaTable.ORG_DOMAIN,
  MetaTable.ORG,
  MetaTable.ORGS_OLD,

  // User-related
  MetaTable.MAIL_SENDS,
  MetaTable.BOOKMARKS,
  MetaTable.BOOKMARK_GROUPS,
  MetaTable.API_TOKEN_SCOPES,
  MetaTable.API_TOKENS,
  MetaTable.PROJECT_USERS,
  MetaTable.WORKSPACE_USER,
  MetaTable.USER_REFRESH_TOKENS,
  MetaTable.USERS,

  // OAuth
  MetaTable.OAUTH_AUTHORIZATION_CODES,
  MetaTable.OAUTH_TOKENS,
  MetaTable.OAUTH_CLIENTS,

  // SSO
  MetaTable.SSO_CLIENT_DOMAIN,
  MetaTable.SSO_CLIENT,

  // Notification / Comments
  MetaTable.NOTIFICATION,
  MetaTable.COMMENTS_REACTIONS,
  MetaTable.USER_COMMENTS_NOTIFICATIONS_PREFERENCE,
  MetaTable.COMMENTS,

  // View types (children before parents)
  MetaTable.MAP_VIEW_COLUMNS,
  MetaTable.MAP_VIEW,
  MetaTable.LIST_VIEW_COLUMNS,
  MetaTable.LIST_VIEW_LEVELS,
  MetaTable.LIST_VIEW,
  MetaTable.KANBAN_VIEW_COLUMNS,
  MetaTable.KANBAN_VIEW,
  MetaTable.CALENDAR_VIEW_COLUMNS,
  MetaTable.CALENDAR_VIEW_RANGE,
  MetaTable.CALENDAR_VIEW,
  MetaTable.TIMELINE_VIEW_COLUMNS,
  MetaTable.TIMELINE_VIEW_RANGE,
  MetaTable.TIMELINE_VIEW,
  MetaTable.GANTT_VIEW_COLUMNS,
  MetaTable.GANTT_VIEW,
  MetaTable.GRID_VIEW_COLUMNS,
  MetaTable.GRID_VIEW,
  MetaTable.GALLERY_VIEW_COLUMNS,
  MetaTable.GALLERY_VIEW,
  MetaTable.FORM_VIEW_COLUMNS,
  MetaTable.FORM_VIEW,
  MetaTable.SHARED_VIEWS,
  MetaTable.VIEW_SECTIONS,
  MetaTable.BASE_SECTIONS,

  // Sort / Filter / Hook
  MetaTable.ROW_COLOR_CONDITIONS,
  MetaTable.SORT,
  MetaTable.FILTER_EXP,
  MetaTable.HOOK_LOGS,
  MetaTable.HOOK_TRIGGER_FIELDS,
  MetaTable.HOOKS,
  MetaTable.VIEWS,

  // Column subtypes (children before parent)
  MetaTable.COL_FORMULA,
  MetaTable.COL_ROLLUP,
  MetaTable.COL_LOOKUP,
  MetaTable.COL_SELECT_OPTIONS,
  MetaTable.COL_RELATIONS,
  MetaTable.COL_PROPS,
  MetaTable.COL_QRCODE,
  MetaTable.COL_BARCODE,
  MetaTable.COL_LONG_TEXT,
  MetaTable.COL_BUTTON,
  MetaTable.COLUMN_VALIDATIONS,
  MetaTable.COLUMNS,

  MetaTable.TRASH,

  // Model-related
  MetaTable.RECORD_TEMPLATES,
  MetaTable.DEPENDENCY_TRACKER,
  MetaTable.MODEL_STAT,
  MetaTable.CUSTOM_URLS,
  MetaTable.MCP_TOKENS,
  MetaTable.DOC_REVISIONS,
  MetaTable.DOCS,
  MetaTable.DOC_CONTENT,
  MetaTable.MODELS,

  // Dashboard / Widget
  MetaTable.WIDGET_DB_DEPENDENCIES,
  MetaTable.DASHBOARD_PROJECT_DB_PROJECT_LINKINGS,
  MetaTable.WIDGETS,
  MetaTable.WIDGET,
  MetaTable.DASHBOARDS,
  MetaTable.LAYOUT,

  // Sync
  MetaTable.SYATMOSPHERE_LOGS,
  MetaTable.SYATMOSPHERE_SOURCE,
  MetaTable.SYATMOSPHERE_CONFIGS,
  MetaTable.SYATMOSPHERE_MAPPINGS,
  MetaTable.TABLE_SYNCS,
  MetaTable.TABLE_SYATMOSPHERE_MAPPINGS,
  MetaTable.TABLE_SYATMOSPHERE_COLUMN_MAPPINGS,

  // Integrations / Sources / Project
  MetaTable.INTEGRATIONS_STORE,
  MetaTable.INTEGRATIONS,
  MetaTable.DATA_REFLECTION,
  MetaTable.SOURCES,
  MetaTable.PROJECT,

  // Automations
  MetaTable.AUTOMATION_SUBSCRIBERS,
  MetaTable.AUTOMATION_EXECUTIONS,
  MetaTable.AUTOMATIONS,

  // Payment
  MetaTable.CREDIT_METERING_COUNTERS,
  MetaTable.CREDIT_LEDGER,
  MetaTable.CREDIT_HOLDS,
  MetaTable.CREDIT_GRANTS,
  MetaTable.SUBSCRIPTION_ADDONS,
  MetaTable.SUBSCRIPTIONS,
  MetaTable.ADDONS,
  MetaTable.PLANS,

  // Installations / Sandboxes / Apps
  MetaTable.MANAGED_APP_DEPLOYMENT_LOGS,
  MetaTable.MANAGED_APP_VERSIONS,
  MetaTable.MANAGED_APPS,
  MetaTable.SANDBOX_DEPLOYMENT_LOGS_OLD,
  MetaTable.SANDBOX_VERSIONS_OLD,
  MetaTable.SANDBOXES_OLD,
  MetaTable.SANDBOXES,
  MetaTable.SANDBOX_CHANGELOG,
  MetaTable.INSTALLATIONS,
  MetaTable.GCP_MARKETPLACE_ACCOUNTS,
  MetaTable.GCP_MARKETPLACE_ENTITLEMENTS,

  // Misc standalone
  MetaTable.EXTENSIONS,
  MetaTable.BASE_VARIABLES,
  MetaTable.JOBS,
  MetaTable.FILE_REFERENCES,
  MetaTable.SNAPSHOT,
  MetaTable.SNAPSHOT_SCHEDULE,
  MetaTable.USAGE_STATS,
  MetaTable.DB_SERVERS,
  MetaTable.DB_MUX,
  MetaTable.SCIM_CONFIG,
  MetaTable.RLS_POLICY_SUBJECTS,
  MetaTable.RLS_POLICIES,

  // Workspace-scoped
  MetaTable.BOOK,
  MetaTable.FOLLOWER,
  MetaTable.COWRITER,
  MetaTable.WORKSPACE,
  MetaTable.STORE,
];

export const sakilaTableNames = [
  'actor',
  'address',
  'category',
  'city',
  'country',
  'customer',
  'film',
  'film_actor',
  'film_category',
  'film_text',
  'inventory',
  'language',
  'payment',
  'rental',
  'staff',
  'store',
  'actor_info',
  'customer_list',
  'film_list',
  'nicer_but_slower_film_list',
  'sales_by_film_category',
  'sales_by_store',
  'staff_list',
];

export enum CacheScope {
  PROJECT = 'base',
  SOURCE = 'source',
  MODEL = 'model',
  COLUMN = 'column',
  COL_PROP = 'colProp',
  COL_RELATION = 'colRelation',
  COL_SELECT_OPTION = 'colSelectOption',
  COL_LOOKUP = 'colLookup',
  COL_ROLLUP = 'colRollup',
  COL_FORMULA = 'colFormula',
  COL_QRCODE = 'colQRCode',
  COL_BARCODE = 'colBarcode',
  COL_LONG_TEXT = 'colLongText',
  FILTER_EXP = 'filterExp',
  SORT = 'sort',
  SHARED_VIEW = 'sharedView',
  ACL = 'acl',
  FORM_VIEW = 'formView',
  FORM_VIEW_COLUMN = 'formViewColumn',
  GALLERY_VIEW = 'galleryView',
  GALLERY_VIEW_COLUMN = 'galleryViewColumn',
  GRID_VIEW = 'gridView',
  GRID_VIEW_COLUMN = 'gridViewColumn',
  KANBAN_VIEW = 'kanbanView',
  CALENDAR_VIEW = 'calendarView',
  CALENDAR_VIEW_COLUMN = 'calendarViewColumn',
  CALENDAR_VIEW_RANGE = 'calendarViewRange',
  TIMELINE_VIEW = 'timelineView',
  TIMELINE_VIEW_COLUMN = 'timelineViewColumn',
  TIMELINE_VIEW_RANGE = 'timelineViewRange',
  GANTT_VIEW = 'ganttView',
  GANTT_VIEW_COLUMN = 'ganttViewColumn',
  MAP_VIEW = 'mapView',
  MAP_VIEW_COLUMN = 'mapViewColumn',
  KANBAN_VIEW_COLUMN = 'kanbanViewColumn',
  LIST_VIEW = 'listView',
  LIST_VIEW_COLUMN = 'listViewColumn',
  LIST_VIEW_LEVEL = 'listViewLevel',
  DATE_DEPENDENCY = 'dateDependency',
  USER = 'user',
  ORGS_OLD = 'orgs',
  TEAM = 'team',
  TEAM_USER = 'teamUser',
  VIEW = 'view',
  AUDIT = 'audit',
  HOOK = 'hook',
  PLUGIN = 'plugin',
  BASE_USER = 'baseUser',
  MODEL_ROLE_VISIBILITY = 'modelRoleVisibility',
  API_TOKEN = 'apiToken',
  BOOKMARK_GROUP = 'bookmarkGroup',
  BOOKMARK = 'bookmark',
  INSTANCE_META = 'instanceMeta',
  USER_BASE = 'userBase',
  DASHBOARD_PROJECT_DB_PROJECT_LINKING = 'dashboardProjectDBProjectLinking',
  // Versioned suffix invalidates all previously cached single-query entries
  // when the cache shape changes — bumping it forces a fresh cache key
  // namespace so stale entries from older deployments are ignored automatically.
  // _v3: v2 entries written without the parentKeys back-link may be orphaned
  // (unreachable by clearSingleQueryCache); never read them again — they stop
  // getting TTL-refreshed and expire on their own.
  // _v4: lookup-of-LTAR payloads now include the custom display value column —
  // queries compiled before that fix would keep serving pk+pv-only JSON.
  SINGLE_QUERY = 'singleQuery_v4',
  JOBS = 'atm_jobs',
  JOBS_POLLING = 'atm_jobs_polling',
  PRESIGNED_URL = 'presignedUrl',
  STORE = 'store',
  PROJECT_ALIAS = 'baseAlias',
  MODEL_ALIAS = 'modelAlias',
  VIEW_ALIAS = 'viewAlias',
  SSO_CLIENT = 'ssoClient',
  EXTENSION = 'uiExtension',
  BASE_VARIABLE = 'baseVariable',
  INTEGRATION = 'integration',
  COL_BUTTON = 'colButton',
  CMD_PALETTE = 'cmdPalette',
  PRODUCT_FEED = 'productFeed',
  SNAPSHOT = 'snapshot',
  SNAPSHOT_SCHEDULE = 'snapshotSchedule',
  DATA_REFLECTION = 'dataReflection',
  CUSTOM_URLS = 'customUrls',
  SCRIPTS = 'atm_scripts',
  SYATMOSPHERE_CONFIGS = 'syncConfigs',
  SYATMOSPHERE_MAPPINGS = 'syncMappings',
  TABLE_SYNC = 'tableSync',
  TABLE_SYATMOSPHERE_MAPPING = 'tableSyncMapping',
  TABLE_SYATMOSPHERE_COLUMN_MAPPING = 'tableSyncColumnMapping',
  USAGE_STATS = 'usageStats',
  RESOURCE_STATS = 'resourceStats',
  STORAGE_STATS = 'storageStats',
  CLOUD_FEATURES = 'cloudFeatures',
  MCP_TOKEN = 'mcpToken',
  DB_SERVERS = 'dbServers',
  PERMISSION = 'permission',
  PERMISSION_USER = 'permissionUser',
  PRINCIPAL = 'principal',
  PRINCIPAL_ASSIGNMENT = 'principalAssignment',
  DASHBOARD = 'dashboard',
  WIDGET = 'widget',
  INTERFACE = 'interface',
  INTERFACE_PAGE = 'interfacePage',
  OAUTH_CLIENT = 'oAuthClient',
  OAUTH_AUTH_CODE = 'oAuthAuthCode',
  OAUTH_TOKEN = 'oAuthToken',
  TEMPLATES = 'templates',
  WORKFLOW = 'atm_workflow',
  WORKFLOW_EXECUTION = 'atm_workflow_execution',
  PRESENCE = 'presence',
  FOCUS = 'focus',
  DOC_LIVE = 'docLive',
  DOC_BOOTSTRAP = 'docBootstrap',
  DOC_PERSIST_LOCK = 'docPersistLock',
  WORKFLOW_WEBHOOK_TEST_LISTENER = 'atm_workflow_webhook_test_listener',
  DEPENDENCY_TRACKER = 'atm_dependency_tracker',
  INSTALLATION = 'installation',
  INSTALLATION_ALIAS = 'installationAlias',
  GCP_MARKETPLACE_ACCOUNT = 'gcpMarketplaceAccount',
  GCP_MARKETPLACE_ACCOUNT_ALIAS = 'gcpMarketplaceAccountAlias',
  GCP_MARKETPLACE_ENTITLEMENT = 'gcpMarketplaceEntitlement',
  GCP_MARKETPLACE_ENTITLEMENT_ALIAS = 'gcpMarketplaceEntitlementAlias',
  MANAGED_APP = 'managedApp',
  MANAGED_APP_VERSION = 'managedAppVersion',
  MANAGED_APP_DEPLOYMENT_LOG = 'managedAppDeploymentLog',
  SUBSCRIPTIONS_ALIAS = 'subscriptionsAlias',
  ADDONS = 'addons',
  SUBSCRIPTION_ADDONS = 'subscriptionAddons',
  AUTOMATION_SUBSCRIBER = 'automationSubscriber',
  SANDBOX = 'sandbox',
  SCIM_CONFIG = 'scimConfig',
  RECORD_TEMPLATE = 'recordTemplate',
  RLS_POLICY = 'rlsPolicy',
  VIEW_SECTION = 'viewSection',
  BASE_SECTION = 'baseSection',
  CHAT_SESSION = 'chatSession',
  DOCUMENT = 'document',
  DOC_CONTENT = 'docContent',
  API_TOKEN_SCOPE = 'apiTokenScope',
  TRASH = 'trash',
}

export enum CacheGetType {
  TYPE_ARRAY = 'TYPE_ARRAY',
  TYPE_OBJECT = 'TYPE_OBJECT',
  TYPE_STRING = 'TYPE_STRING',
}

export enum CacheDelDirection {
  PARENT_TO_CHILD = 'PARENT_TO_CHILD',
  CHILD_TO_PARENT = 'CHILD_TO_PARENT',
}

export const DB_TYPES = <const>[
  'mysql2',
  'sqlite3',
  'mysql',
  'snowflake',
  'pg',
  'databricks',
];

export enum RootScopes {
  ROOT = 'root',
  ORG = 'org',
  WORKSPACE = 'workspace',
  BASE = 'base',
  // This scope only used for extract-ids middleware to get initial entity
  BYPASS = 'bypass',
  // BYPASS only meant for v2 bases now, we will use FULL_BYPASS for other full bypass scenarios like shared base/view (get with uuid)
  FULL_BYPASS = 'full_bypass',
}

export const RootScopeTables = {
  [RootScopes.ROOT]: [
    MetaTable.USERS,
    MetaTable.USER_REFRESH_TOKENS,
    MetaTable.API_TOKENS,
    MetaTable.API_TOKEN_SCOPES,
    MetaTable.FOLLOWER,
    MetaTable.PLUGIN,
    MetaTable.DB_MUX,
    MetaTable.STORE,
    MetaTable.NOTIFICATION,
    MetaTable.JOBS,
    MetaTable.FILE_REFERENCES,
    MetaTable.DATA_REFLECTION,
    MetaTable.MANAGED_APPS,
    MetaTable.MANAGED_APP_VERSIONS,
    MetaTable.MANAGED_APP_DEPLOYMENT_LOGS,
    MetaTable.SANDBOXES,
    // Temporarily added need to be discussed within team
    MetaTable.AUDIT,
    MetaTable.CUSTOM_URLS,
    MetaTable.MCP_TOKENS,
    MetaTable.OAUTH_CLIENTS,
    MetaTable.OAUTH_AUTHORIZATION_CODES,
    MetaTable.OAUTH_TOKENS,
    MetaTable.TEAMS,
    MetaTable.BOOKMARK_GROUPS,
    MetaTable.BOOKMARKS,
    MetaTable.MAIL_SENDS,
  ],
  [RootScopes.ORG]: [
    MetaTable.ORG,
    MetaTable.ORG_DOMAIN,
    MetaTable.ORG_USERS,
    MetaTable.SSO_CLIENT,
    MetaTable.SSO_CLIENT_DOMAIN,
  ],
  [RootScopes.WORKSPACE]: [
    MetaTable.WORKSPACE,
    MetaTable.WORKSPACE_USER,
    MetaTable.INTEGRATIONS,
    MetaTable.SOURCES,
    // We need to clear fk_integration_id from following tables
    MetaTable.COL_BUTTON,
    MetaTable.COL_LONG_TEXT,

    MetaTable.PRINCIPAL_ASSIGNMENTS,
    MetaTable.SCIM_CONFIG,
  ],
  [RootScopes.BASE]: [MetaTable.PROJECT],
};

export const CACHE_PREFIX =
  process.env.ATMOSPHERE_CACHE_PREFIX && process.env.ATMOSPHERE_CACHE_PREFIX.trim().length > 0
    ? process.env.ATMOSPHERE_CACHE_PREFIX
    : 'atm';

export enum FilterCacheScope {
  VIEW = 'view',
  HOOK = 'hook',
  COLUMN = 'column',
  PARENT_COLUMN = 'parentColumn',
  LINK_COL = 'linkCol',
  WIDGET = 'widget',
  PARENT = 'parent',
  RLS_POLICY = 'rlsPolicy',
  BUTTON_COLUMN = 'buttonColumn',
}

export const ATMOSPHERE_STORE_DEFAULT_WORKSPACE_ID_KEY = 'ATMOSPHERE_DEFAULT_WORKSPACE_ID';
export const ATMOSPHERE_STORE_DEFAULT_ORG_ID_KEY = 'ATMOSPHERE_DEFAULT_ORG_ID';
export { ATMOSPHERE_DEFAULT_ORG_ID } from 'atmosphere-sdk';

export enum ResourceType {
  ORG = 'org',
  WORKSPACE = 'workspace',
  BASE = 'base',
  TEAM = 'team',
  INTERFACE = 'interface',
  INTERFACE_PAGE = 'interfacePage',
}

export enum PrincipalType {
  USER = 'user',
  TEAM = 'team',
  BOT = 'bot',
  GROUP = 'group',
  SERVICE = 'service',
}
