/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import type { IntegrationEntry } from '@atmosphere-local-integrations/core';

export default [] as IntegrationEntry[];
